name: Build and Deploy WebGL to GitHub Pages

on:
  push:
    branches:
      - test-ci  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - test-ci

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Debug: Print expected project path and check for Assets subfolder
    - name: Check Project Path and Assets folder
      run: |
        echo "Expected project path: ./Alien Influencer"
        echo "Current directory contents:"
        ls -la
        echo "Checking if Assets folder exists in the expected project path..."
        if [ -d "./Alien Influencer/Assets" ]; then
          echo "Assets folder found in './Alien Influencer'"
        else
          echo "Assets folder NOT found in './Alien Influencer'."
        fi
        echo "Checking the contents of the expected project path:"
        ls -la "./Alien Influencer"


    # Set up Unity for building
    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        version: 2022.3.7f1
        targetPlatform: WebGL


    # Build the project in Alien Influencer directory
    - name: Build WebGL
      run: |
        mkdir -p build
        unity-editor -batchmode -nographics -quit \
        -projectPath "./Alien Influencer" \
        -buildTarget WebGL \
        -executeMethod BuildScript.PerformBuild \
        -buildPath build/WebGL/

    # Upload the WebGL build to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/WebGL
        publish_branch: gh-pages
